---
# This Playbook does the following things in order

# prepare_node.yml
#  * It will run on both controller and compute node.
#  - Add the host to tripleo-inventory
#  - Run undercloud-setup
- import_tasks: prepare_node.yml

# deploy_standalone.yml
#  * It will run on controller node
#  - Deploy Standalone
#  - Generate 99 standalone vars
- import_tasks: deploy_standalone.yml
  when: deploy_standalone | bool

# compute_services_on_target_host.yml
#   * It will run on target node.
#   - Install the tripleo-ansible dependencies on target node
#   - Copy 99 standalone vars from controller to
#     compute node inventory
#   - Deploy compute services on target node
- import_tasks: compute_services_on_target_host.yml
  when: not deploy_standalone | bool
