---
- name: Rerun container image prepare for mixed OS compute deployment
  hosts: undercloud
  gather_facts: false
  tags:
    - overcloud-prep-containers
  roles:
    - role: overcloud-prep-containers
  tasks:
    - name: Resolve dlrn_hash for periodic jobs (no content provider)
      when: not job.consumer_job | default(false) | bool
      block:
        - include_role:
            name: repo-setup
            tasks_from: tripleo-get-hash-set-fact.yml
          vars:
            search_tag: "{{ dlrn_hash_tag }}"
            fact_name: "dlrn_hash"
        - name: "debug d_h_t {{ dlrn_hash_tag }} c_b_id {{ container_build_id }} d_h {{ dlrn_hash }}"
          debug:
            msg: "d_h_t {{ dlrn_hash_tag }} c_b_id {{ container_build_id }} d_h {{ dlrn_hash }}  "
        - name: "set fact for container_build_id with resolved dlrn_hash {{ dlrn_hash }}"
          set_fact:
            container_build_id: "{{ dlrn_hash }}"
            cacheable: true
    - name: set fact for container_build_id with dlrn_hash_tag {{ dlrn_hash_tag }} from content provider
      when: job.consumer_job | default(false) | bool
      set_fact:
        container_build_id: "{{ dlrn_hash_tag }}"
        cacheable: true
    - name: "Recreate containers-prepare-parameter file "
      include_role:
        name: undercloud-deploy
        tasks_from: create-scripts.yml
    - name: Run container image prepare for compute deploy
      shell: |
        source /home/zuul/stackrc
        sudo openstack tripleo container image prepare -e /home/zuul/containers-prepare-parameter.yaml --log-file /var/log/tripleo-container-image-prepare-compute.log --debug

- name: Deploy the overcloud compute stack
  hosts: undercloud
  gather_facts: false
  environment:
    TRIPLEO_ROOT: "{{ lookup('env','TRIPLEO_ROOT') }}"
  tasks:
    - name: Deploy the overcloud
      include_role:
        name: overcloud-deploy
      vars:
        overcloud_roles: "{{ overcloud_roles_compute }}"
        topology_map: "{{ topology_map_compute }}"
        extra_args: " -e /home/zuul/overcloud-deploy/overcloud/overcloud-export.yaml --disable-protected-resource-types --baremetal-deployment "
      tags:
        - overcloud-deploy

    - name: Check the overcloud_deployment_result.json if this is CI job
      tags:
        - overcloud-deploy
      block:
        - name: ensure the deployment result has been read into memory
          include_vars: "{{ local_working_dir }}/overcloud_deployment_result.json"
          delegate_to: localhost

        # overcloud_deploy_result = ["failed", "passed"]
        - name: did the deployment pass or fail?
          debug: var=overcloud_deploy_result
          failed_when: overcloud_deploy_result == "failed"
          delegate_to: localhost

- name: nova cell_v2 discover_hosts on Controller after Compute deployment
  hosts: overcloud_control
  tags:
    - overcloud-deploy
  tasks:
    - name: Run nova-manage cell_v2 discover_hosts
      shell: |
        sudo podman exec nova_api nova-manage cell_v2 discover_hosts --by-service --verbose
    - name: DEBUG nova-manage cell_v2 list_hosts
      shell: |
        sudo podman exec nova_api nova-manage cell_v2 list_hosts
      register: nova_manage_cell_debug
    - name: debug nova-manage output
      debug:
        msg: "DEBUG output of cell_v2 list_hosts after discovery {{ nova_manage_cell_debug.stdout_lines }}"
