---
- name: "Delete overcloud"
  tags:
    - overcloud-delete
  block:
    - name: "Get overcloud id"
      shell: >-
        source {{ working_dir }}/stackrc && \
        openstack stack list -f value -c ID
      environment:
        OVERCLOUD_NAME: "{{ stack_name }}"
      register: overcloud_id

    - name: "Run overcloud delete"
      when:
        - step_delete_overcloud | bool
      collections:
        - tripleo.operator
      include_role:
        name: tripleo_overcloud_delete
      vars:
        tripleo_overcloud_delete_debug: true
        tripleo_overcloud_delete_name: "{{ stack_name }}"
        tripleo_overcloud_delete_rc_file: "{{ working_dir }}/stackrc"
        tripleo_overcloud_delete_log: "{{ delete_log }}"

    - name: "check for delete command to complete or fail"
      when:
        - step_delete_overcloud | bool
      shell: |
        source {{ working_dir }}/stackrc
        openstack stack show {{ overcloud_id }} -f yaml
      delay: "{{ delete_check_delay }}"
      retries: "{{ delete_check_retries }}"
      until: heat_stack_show.stdout.find('DELETE_COMPLETE') != -1
      register: heat_stack_show
